"""extend league to 4-6 players

Revision ID: 00728e8967f4
Revises: 0e6a82b8f6f3
Create Date: 2026-03-05 20:42:19.354109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00728e8967f4'
down_revision = '0e6a82b8f6f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league', schema=None) as batch_op:
        batch_op.add_column(sa.Column('p6', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('p1p6', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('p2p6', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('p3p6', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('p4p6', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('p5p6', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('p6p1', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('p6p2', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('p6p3', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('p6p4', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('p6p5', sa.Integer(), nullable=True))
        batch_op.alter_column('p5',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('league', schema=None) as batch_op:
        batch_op.alter_column('p5',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('p6p5')
        batch_op.drop_column('p6p4')
        batch_op.drop_column('p6p3')
        batch_op.drop_column('p6p2')
        batch_op.drop_column('p6p1')
        batch_op.drop_column('p5p6')
        batch_op.drop_column('p4p6')
        batch_op.drop_column('p3p6')
        batch_op.drop_column('p2p6')
        batch_op.drop_column('p1p6')
        batch_op.drop_column('p6')

    # ### end Alembic commands ###
