"""add scutta_count and scutta_change

Revision ID: 0e6a82b8f6f3
Revises: 00bd16465ddb
Create Date: 2026-03-05 16:22:59.587112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e6a82b8f6f3'
down_revision = '00bd16465ddb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scutta_count', sa.Integer(), server_default='0', nullable=True))
        batch_op.add_column(sa.Column('scutta_order', sa.Integer(), nullable=True))

    with op.batch_alter_table('player_point_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scutta_change', sa.Integer(), server_default='0', nullable=True))

    # 기존 데이터의 NULL을 0으로 업데이트
    op.execute("UPDATE player SET scutta_count = 0 WHERE scutta_count IS NULL")
    op.execute("UPDATE player_point_log SET scutta_change = 0 WHERE scutta_change IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_point_log', schema=None) as batch_op:
        batch_op.drop_column('scutta_change')

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_column('scutta_order')
        batch_op.drop_column('scutta_count')

    # ### end Alembic commands ###
