"""Create initial tables

Revision ID: 189e0722533a
Revises: 
Create Date: 2025-08-24 21:13:10.654307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '189e0722533a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('league',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('p1', sa.String(length=100), nullable=False),
    # sa.Column('p2', sa.String(length=100), nullable=False),
    # sa.Column('p3', sa.String(length=100), nullable=False),
    # sa.Column('p4', sa.String(length=100), nullable=False),
    # sa.Column('p5', sa.String(length=100), nullable=False),
    # sa.Column('p1p2', sa.Integer(), nullable=True),
    # sa.Column('p1p3', sa.Integer(), nullable=True),
    # sa.Column('p1p4', sa.Integer(), nullable=True),
    # sa.Column('p1p5', sa.Integer(), nullable=True),
    # sa.Column('p2p1', sa.Integer(), nullable=True),
    # sa.Column('p2p3', sa.Integer(), nullable=True),
    # sa.Column('p2p4', sa.Integer(), nullable=True),
    # sa.Column('p2p5', sa.Integer(), nullable=True),
    # sa.Column('p3p1', sa.Integer(), nullable=True),
    # sa.Column('p3p2', sa.Integer(), nullable=True),
    # sa.Column('p3p4', sa.Integer(), nullable=True),
    # sa.Column('p3p5', sa.Integer(), nullable=True),
    # sa.Column('p4p1', sa.Integer(), nullable=True),
    # sa.Column('p4p2', sa.Integer(), nullable=True),
    # sa.Column('p4p3', sa.Integer(), nullable=True),
    # sa.Column('p4p5', sa.Integer(), nullable=True),
    # sa.Column('p5p1', sa.Integer(), nullable=True),
    # sa.Column('p5p2', sa.Integer(), nullable=True),
    # sa.Column('p5p3', sa.Integer(), nullable=True),
    # sa.Column('p5p4', sa.Integer(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('player',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(length=100), nullable=False),
    # sa.Column('is_valid', sa.Boolean(), nullable=True),
    # sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='genderenum'), nullable=True),
    # sa.Column('previous_rank', sa.Integer(), nullable=True),
    # sa.Column('rank_change', sa.String(length=10), nullable=True),
    # sa.Column('rank', sa.Integer(), nullable=True),
    # sa.Column('match_count', sa.Integer(), nullable=True),
    # sa.Column('win_count', sa.Integer(), nullable=True),
    # sa.Column('loss_count', sa.Integer(), nullable=True),
    # sa.Column('rate_count', sa.Float(), nullable=True),
    # sa.Column('opponent_count', sa.Integer(), nullable=True),
    # sa.Column('achieve_count', sa.Integer(), nullable=True),
    # sa.Column('betting_count', sa.Integer(), nullable=True),
    # sa.Column('win_order', sa.Integer(), nullable=True),
    # sa.Column('loss_order', sa.Integer(), nullable=True),
    # sa.Column('match_order', sa.Integer(), nullable=True),
    # sa.Column('rate_order', sa.Integer(), nullable=True),
    # sa.Column('opponent_order', sa.Integer(), nullable=True),
    # sa.Column('achieve_order', sa.Integer(), nullable=True),
    # sa.Column('betting_order', sa.Integer(), nullable=True),
    # sa.Column('is_she_or_he_freshman', sa.Enum('YES', 'No', name='freshmanenum'), nullable=True),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('name')
    # )
    # op.create_table('tournament',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('title', sa.String(length=150), nullable=False),
    # sa.Column('status', sa.String(length=20), nullable=False),
    # sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    # sa.Column('bracket_data', sa.JSON(), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('update_log',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('title', sa.String(length=100), nullable=False),
    # sa.Column('html_content', sa.Text(), nullable=False),
    # sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('match',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('winner', sa.Integer(), nullable=False),
    # sa.Column('winner_name', sa.String(length=100), nullable=False),
    # sa.Column('loser', sa.Integer(), nullable=False),
    # sa.Column('loser_name', sa.String(length=100), nullable=False),
    # sa.Column('score', sa.String(length=10), nullable=False),
    # sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    # sa.Column('approved', sa.Boolean(), nullable=True),
    # sa.ForeignKeyConstraint(['loser'], ['player.id'], ),
    # sa.ForeignKeyConstraint(['winner'], ['player.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('player_point_log',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('player_id', sa.Integer(), nullable=False),
    # sa.Column('achieve_change', sa.Integer(), nullable=True),
    # sa.Column('betting_change', sa.Integer(), nullable=True),
    # sa.Column('reason', sa.String(length=100), nullable=False),
    # sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    # sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('today_partner',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('p1_id', sa.Integer(), nullable=False),
    # sa.Column('p1_name', sa.String(length=100), nullable=False),
    # sa.Column('p2_id', sa.Integer(), nullable=False),
    # sa.Column('p2_name', sa.String(length=100), nullable=False),
    # sa.Column('submitted', sa.Boolean(), nullable=True),
    # sa.ForeignKeyConstraint(['p1_id'], ['player.id'], ),
    # sa.ForeignKeyConstraint(['p2_id'], ['player.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_table('user',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('username', sa.String(length=64), nullable=True),
    # sa.Column('password_hash', sa.String(length=256), nullable=True),
    # sa.Column('is_admin', sa.Boolean(), nullable=True),
    # sa.Column('player_id', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    # sa.PrimaryKeyConstraint('id')
    # )
    # with op.batch_alter_table('user', schema=None) as batch_op:
    #     batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('betting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('p1_id', sa.Integer(), nullable=False),
    sa.Column('p1_name', sa.String(length=100), nullable=False),
    sa.Column('p2_id', sa.Integer(), nullable=False),
    sa.Column('p2_name', sa.String(length=100), nullable=False),
    sa.Column('point', sa.Integer(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('submitted', sa.Boolean(), nullable=True),
    sa.Column('result', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['p1_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['p2_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['result'], ['match.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('betting_participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('betting_id', sa.Integer(), nullable=False),
    sa.Column('participant_name', sa.String(length=100), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['betting_id'], ['betting.id'], ),
    sa.ForeignKeyConstraint(['participant_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('betting_participant')
    op.drop_table('betting')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    op.drop_table('today_partner')
    op.drop_table('player_point_log')
    op.drop_table('match')
    op.drop_table('update_log')
    op.drop_table('tournament')
    op.drop_table('player')
    op.drop_table('league')
    # ### end Alembic commands ###
