"""add indexes to betting_participant and point_log

Revision ID: 8bd538ee9407
Revises: c2de87e01e7c
Create Date: 2026-04-09 14:47:57.533987

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bd538ee9407'
down_revision = 'c2de87e01e7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('betting_participant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_betting_participant_betting_id'), ['betting_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_betting_participant_participant_id'), ['participant_id'], unique=False)

    with op.batch_alter_table('player_point_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_point_log_player_id'), ['player_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_point_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_point_log_player_id'))

    with op.batch_alter_table('betting_participant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_betting_participant_participant_id'))
        batch_op.drop_index(batch_op.f('ix_betting_participant_betting_id'))

    # ### end Alembic commands ###
