"""Add Tournament table

Revision ID: 98462be24540
Revises: 934009fc86ed
Create Date: 2025-08-22 00:32:40.213651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98462be24540'
down_revision = '934009fc86ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tournament',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('bracket_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tournament')
    # ### end Alembic commands ###
