"""add indexes for performance

Revision ID: c2de87e01e7c
Revises: 00728e8967f4
Create Date: 2026-03-13 00:43:53.517964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2de87e01e7c'
down_revision = '00728e8967f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('betting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_betting_result'), ['result'], unique=False)

    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_approved'), ['approved'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_loser'), ['loser'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_winner'), ['winner'], unique=False)

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_is_valid'), ['is_valid'], unique=False)

    with op.batch_alter_table('today_partner', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_today_partner_p1_id'), ['p1_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_today_partner_p2_id'), ['p2_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_today_partner_submitted'), ['submitted'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('today_partner', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_today_partner_submitted'))
        batch_op.drop_index(batch_op.f('ix_today_partner_p2_id'))
        batch_op.drop_index(batch_op.f('ix_today_partner_p1_id'))

    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_is_valid'))

    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_winner'))
        batch_op.drop_index(batch_op.f('ix_match_timestamp'))
        batch_op.drop_index(batch_op.f('ix_match_loser'))
        batch_op.drop_index(batch_op.f('ix_match_approved'))

    with op.batch_alter_table('betting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_betting_result'))

    # ### end Alembic commands ###
