"""empty message

Revision ID: e3aeb63c0ea6
Revises: 189e0722533a
Create Date: 2025-09-15 00:29:58.358687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3aeb63c0ea6'
down_revision = '189e0722533a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('betting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_closed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('betting', schema=None) as batch_op:
        batch_op.drop_column('is_closed')

    # ### end Alembic commands ###
